Homework 1
ddragic5/android-vjestina-tmdb pull request #1
Opened 2023-03-24 19:34 UTC by ddragic5

2023-03-27 15:07 UTC, msalkovic98 requested changes
Generally well done homework, but formatting is very bad. Please refer to [Kotlin code style conventions](https://kotlinlang.org/docs/coding-conventions.html) and use auto formatting when making changes. It will make future reviews and changes much easier.

2023-03-27 15:07 UTC, msalkovic98 commented on app/build.gradle
> +    }
Most of these are already specified, no need to duplicate.

2023-03-27 15:07 UTC, msalkovic98 commented on app/build.gradle
> +    implementation("androidx.compose.material:material:1.3.1")
Rather increase bom to latest `androidx.compose:compose-bom:2023.03.00` than increase single dependency.

2023-03-27 15:07 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ActorCard.kt
> +        shape= RoundedCornerShape(20.dp),
I would suggest you to use `MaterialTheme.spacing` instead of number values for dimensions. If there is no appropriate dimension defined, you can define your own. Dimensions such as 15.dp can be rounded to closest power of 2, i.e. 16.dp. It is not mandatory for sizes to be powers of 2, but it is advised that all dimensions are divisible by 4. Exception is 2.dp if needed. Rounding should be done only for dp, not for sp i.e. text sizes.

2023-03-27 15:07 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ActorCard.kt
> +            Column() {
No need to write empty parentheses when lambda is only argument.

2023-03-27 15:07 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ActorCard.kt
> +            modifier = Modifier.weight(0.5F),
If you set weight on only one element, it will fill all available space. Then it doesn't matter which value you specify, so convention is to use `weight(1f)`.  If more elements would have weights set, then their heights would be proportional to set values.

2023-03-27 15:07 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ActorCard.kt
> +    val actorCardViewState = ActorCardViewState(name ="Robert Downey Jr." , imageUrl = "https://media1.popsugar-assets.com/files/thumbor/HwtAUAufmAZv-FgGEIMJS2eQM-A/0x1:2771x2772/fit-in/2048xorig/fil
You can use data from `MoviesMock`.

2023-03-27 15:07 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ActorCard.kt
> +}
Each file should have an empty line at the end. You can configure Android Studio to add new line at the end of each file automatically by checking `Ensure every saved file ends with a line break` in `File -> Preferences -> Editor -> General`

2023-03-27 15:07 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +            .size(30.dp)
Component shouldn't define its own size, it should be passed from outside through modifier. In this case, you can use `Icon` instead of `Image` to comply with material design standards.

2023-03-27 15:07 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/MovieCard.kt
> +                .padding(5.dp),
Components should not define their relation to other components, so any margin/padding should be provided from caller using modifier.

2023-03-27 15:07 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ProgressBar.kt
> +                color = Color(100, 340, 100),
You can extract colors to util files, there should already be some colors defined.

2023-04-03 10:46 UTC, ddragic5 commented
Hello Matej, 
Sorry it took so long, I had a lot on my plate at work, 
I pushed the asked changes, if everything is okay I'd like to merge first homework. I started the 2nd homework today, so I think I'll finish it on time

2023-04-04 09:23 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ActorCard.kt
> +        }
No need to nest two columns, one is enough.

2023-04-04 09:23 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +            .size(30.dp)
Not resolved

2023-04-04 09:23 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/MovieCategoryLabel.kt
> +    {
Wrong formatting.

2023-04-04 09:23 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ActorCard.kt
> +        shape= RoundedCornerShape(20.dp),
Not resolved

2023-04-04 09:24 UTC, msalkovic98 commented on app/build.gradle
> +    }
Not resolved

2023-04-04 09:25 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +            .size(30.dp)
Not resolved

2023-04-04 09:26 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/ActorCard.kt
> +}
Resolved only in few files, but not in all

2023-04-11 10:54 UTC, msalkovic98 approved these changes
Fix minor issue, then merge

2023-04-11 10:54 UTC, msalkovic98 commented on app/src/main/java/endava/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +        .padding(MaterialTheme.spacing.small),
Default modifier should be empty, size and padding should be defined from outside

2023-04-25 09:13 UTC, merged